### ISSUE TITLE
按照ReadMe.md内的方法安装失败

### ISSUE THREAD

**Issue by CocodyChou** [answer-huang/dSYMTools#10]

**Comment by answer-huang** [comment]
请问失败提示什么。

**Comment by CocodyChou** [comment]
Traceback (most recent call last):
  File "/Applications/dSYM.app/Contents/Resources/RunScript.py", line 18, in <module>
    print os.environ["EFFECTIVE_PLATFORM_NAME"]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'EFFECTIVE_PLATFORM_NAME'

是不是因为我没有配置一些环境？

**Comment by answer-huang** [comment]
EFFECTIVE_PLATFORM_NAME 这个是 Xcode 执行时候的一个环境变量，应该有的啊。其实这个脚本可以不配置的，手动把 archive 文件保存起来，直接拖到 app 里面就行了。

**Comment by CocodyChou** [comment]
不配置的话启动就退出。这个是正常的吗？Mac OS X 10.4，Mac OS X 11 GM都是这样。

麻烦问下archive拖到App哪个目录下？

谢谢你写的文章和提供的工具，以及答复！

发自我的 iPhone

**Comment by answer-huang** [comment]
app 是独立的，Xcode 的脚本就算不配置也应该能运行起来的，archive 直接拖到 app 的窗口中就可以了。请问你是下的哪个版本。或者给我邮箱，我重发一个新的 app 给你。

**Comment by CocodyChou** [comment]
我下的是Github上的，1.0.3，1.0.1可以启动开。

邮箱 50937936@qq.com 。

谢谢～

发自我的 iPhone

**Comment by answer-huang** [comment]
邮箱有问题，发不出去。

**Comment by CocodyChou** [comment]
Sorry，输入错误。
50937036@qq.com 
如果还是不行，尝试 work_cocody@hotmail.com
谢谢～～～！
