### ISSUE TITLE
程序在最新的 mac 系统 （10.11.1 El Capitan）上打不开

### ISSUE THREAD

**Issue by longbow007** [answer-huang/dSYMTools#11]
求教，难道是我打开方式不对？还是姿势不对？- -b

**Comment by answer-huang** [comment]
1.0.3 版本在 10.11.1 上是没问题的啊，我这儿正常的。

**Comment by TESTSUP** [comment]
同问题，在10.11.1打不开

**Comment by TESTSUP** [comment]
终端执行setup.py提示：error: [Errno 1] Operation not permitted: ，求解决

**Comment by answer-huang** [comment]
@TESTSUP   需要用 py2app 打包的，命令是  python setup.py py2app。

**Comment by TESTSUP** [comment]
我就是这么执行的，还试过：sudo python setup.py py2app ，也是不行

**Comment by answer-huang** [comment]
那应该是环境的问题了。 @TESTSUP

**Comment by 643824979** [comment]
我用的是最新的系统也出现这个问题 error: [Errno 1] Operation not permitted: '/Users/admin/Downloads/dSYMTools-master/dist/dSYM.app/Contents/MacOS/dSYM'
