### ISSUE TITLE
10.11.5 打不开了。

### ISSUE THREAD

**Issue by csc-EricWu** [answer-huang/dSYMTools#15]
楼主，还在维护吗？10.11.5打不开了，

**Comment by answer-huang** [comment]
是用的1.0.3版本吗？我电脑上是可以的。

**Comment by x5forever** [comment]
10.11.5的确系统打不开，忘楼主尽快更新。。。

**Comment by yzxcool123** [comment]
10.11.6可以打开, 是从作者在ReadMe最底部给出的链接下载的, clone下来的源码中的app确实打不开

**Comment by answer-huang** [comment]
最近在用 oc 重写，已经完成70%了。

**Comment by answer-huang** [comment]
已经用 OC 重写了，麻烦下载最新 release 版本 https://github.com/answer-huang/dSYMTools/releases/tag/1.0.4
