### ISSUE TITLE
slide address在哪？

### ISSUE THREAD

**Issue by wybflb** [answer-huang/dSYMTools#17]
请问一下，是否支持Xcode7，崩溃日志中并没有slide address项，网上说是每一行的崩溃信息`0x1001000f8 0x1000f8000 + 33016`中间的那个就是slide address，那么内存地址项如何填写？写哪个得出的结果都不对。

**Comment by answer-huang** [comment]
在崩溃日志里面找到 Binary IImages: 这一块，Binary IImages: 下面第一行就是加载应用可执行文件的信息，大致如下：
Binary Images:
0x1000ac000 - 0x100c13fff yourApp arm64  <e86bcc8875b230279c962186b80b466d> /var/containers/Bundle/Application/99EE6ECE-4CEA-4ADD-AE8D-C4B498886D22/yourApp.app/yourApp。

其中 0x1000ac000 就是 slide address。
arm64  <e86bcc8875b230279c962186b80b466d> 指的是 arm64 架构下，uuid 是 e86bcc8875b230279c962186b80b466d，记得对比下跟你的 archive 文件是否对的上。

**Comment by wybflb** [comment]
如果slide address填写0x1000ac000，那么内存地址的地方是应该写0x100c13fff么？我还是有几点疑问啊，第一个问题是，我之前用此工具分析出了一行的问题，使用的 Last Exception Backtraces下面的内存地址，每行有三个，中间是slide address，第三列是偏移量的那个。但是分析其他行的时候，得不到任何有效的信息，但是用symbolicatecrash是可以的，其次是，这样子需要手动去每一行的内存去复制粘贴，显得略微有些麻烦，分析一个crash文件需要很长时间才行，并没有比symbolicatecrash方便，那么工具的意义是什么？

**Comment by answer-huang** [comment]
slide address 是 0x1000ac000，内存地址应该是 Last Exception Backtraces 中每一行的第一个地址，分析其他行的时候你要看下是不是自己应用可执行文件那行，因为你这个 slide address 只对应到自己那个可执行文件，系统的一些库的 slide address 都不一样的。
其实分析一个 crash 文件并不要很长时间，只需要找到自己可执行文件对应的那行内存地址，slide address，和 arch type 这三个信息就可以了，并不是每一行错误信息都需要看。
这个工具最初是为了解决友盟上错误信息而做的，这样就不需要每次都输入命令行，所以并没有设计支持 crash log，主要是考虑到 Xcode 在 crash log 这块已经会直接转换过去，所以就没做这块功能。

**Comment by wybflb** [comment]
好的，知道了， 谢谢啦

**Comment by bolee** [comment]
这里才算看懂怎么弄了
