### ISSUE TITLE
10.12系统无法打开

### ISSUE THREAD

**Issue by FreshManCode** [answer-huang/dSYMTools#19]
楼主你好,请问在10.12的系统上能否打开?

**Comment by answer-huang** [comment]
可以。

**Comment by YangChaoJie** [comment]
楼主你好，我的在10.12上，打不开啊

**Comment by answer-huang** [comment]
@YangChaoJie  麻烦下载最新 release 版本
 https://github.com/answer-huang/dSYMTools/releases/tag/1.0.4
