### ISSUE TITLE
百度统计错误分析没有slide address应用怎么办呢?

### ISSUE THREAD

**Issue by SenorSamuel** [answer-huang/dSYMTools#20]
友盟是有的,但是百度统计没有

**Comment by answer-huang** [comment]
你好，方便发一个百度统计的错误日志看下吗？

**Comment by SenorSamuel** [comment]
附件一是百度统计的
附件二是友盟统计的,是有slide address,分析错误起来会方便很多




在 2016-10-17 11:13:21，"answer-huang" <notifications@github.com> 写道：


你好，方便发一个百度统计的错误日志看下吗？

**Comment by answer-huang** [comment]
发我邮箱吧（aihoo91@gmail.com），直接回复的邮件看不到附件。

**Comment by allen8300** [comment]
@SenorSamuel 
请问没有slide address情况下，后来怎么办的呢？
