### ISSUE TITLE
dsym文件拖不进去

### ISSUE THREAD

**Issue by yfldj** [answer-huang/dSYMTools#23]
最新版本，如题

**Comment by answer-huang** [comment]
这个版本还不支持 dsym 文件直接拖进去，需要拖入 xcarchive 文件。

**Comment by allen8300** [comment]
您好，master现在仍然不支持sdym文件么？？
我看描述中写道：Version 1.0.1 2014-07-29
1.增加对 dSYM 文件的支持，直接将 xcarchive 或 dSYM 文件拖入窗口中即可。

**Comment by answer-huang** [comment]
> 您好，master现在仍然不支持sdym文件么？？
> 我看描述中写道：Version 1.0.1 2014-07-29
> 1.增加对 dSYM 文件的支持，直接将 xcarchive 或 dSYM 文件拖入窗口中即可。

新版本的可以自己下载源码, 用原声的自己编译一个. 支持 dSYM 的.
