### ISSUE TITLE
没有crash文件如何取到slideaddress

### ISSUE THREAD

**Issue by feiadan** [answer-huang/dSYMTools#25]

**Comment by feiadan** [comment]
单从堆栈信息里可以算出slideaddress吗？

**Comment by feiadan** [comment]
app运行的时候能取到slide address吗？

**Comment by answer-huang** [comment]
要看什么堆栈信息了啊，想友盟这种应该是经过换算的，所以同一种架构的CPU，地址都是一样的，如果是crash log，里面slideaddress是可以算出来的，app运行的时候是能通过 dyld_get_image_vmaddr_slide 方法取到slide address的。
