### ISSUE TITLE
你好，我dsym文件的uuid怎么始终不能对应，友盟后台的uuid和dsym工具不能对应，麻烦支招

### ISSUE THREAD

**Issue by ArronMe** [answer-huang/dSYMTools#27]
<img width="821" alt="2017-01-17 3 12 45" src="https://cloud.githubusercontent.com/assets/16532586/22011000/931f6e3e-dcc7-11e6-9c27-44f18e9598b0.png">
<img width="518" alt="2017-01-17 3 13 23" src="https://cloud.githubusercontent.com/assets/16532586/22011001/95eaea58-dcc7-11e6-8cd5-844197bfe038.png">

**Comment by answer-huang** [comment]
这个肯定是你archive文件错了。
