### ISSUE TITLE
工具如何使用问题

### ISSUE THREAD

**Issue by liumingzhi** [answer-huang/dSYMTools#32]
这个工具默认 Slide Adderss  栏应该填什么呀   错误内存地址是要把未符号出来的地址都写上吗 例如这种 
Last Exception Backtrace:
(0x18e49d1b8 0x18ced455c 0x18e49d100 0x18eeb32e8 0x100946fbc 0x194387d30 0x194387cb0 0x10125ccdc 0x100735a88 0x194372128 0x19438f9f8 0x194912628 0x19490e6c0 0x19490e1e0 0x19490d49c 0x19438230c 0x194352da0 0x194b3c75c 0x194b36130 0x18e44ab5c 0x18e44a4a4 0x18e4480a4 0x18e3762b8 0x18fe2a198 0x1943bd7fc 0x1943b8534 0x10002ad78 0x18d3595b8)

**Comment by answer-huang** [comment]
https://github.com/answer-huang/dSYMTools/issues/17   见这个 issue。
