### ISSUE TITLE
查询到的结果有误

### ISSUE THREAD

**Issue by fanzwd** [answer-huang/dSYMTools#34]
我的工程时一个workspace包含多个project，这些project有一些是framework类型的静态库，这些库导入主工程使用，如果这些framework工程出错，使用这个工具无法定位到正确的位置。

**Comment by answer-huang** [comment]
你好，是可以算出来的，我遇到过这种情况，如果你的错误出在你项目调用的一个framework里面，对应的slideaddress就是这个framework的，是可以通过换算得到你自己项目里面调用framework的地方的，你QQ发我，我可以帮你看下这个问题。

**Comment by fanzwd** [comment]
有点不好意思，已经下班了，想知道如何知道这个framework的slideaddress

**Comment by fanzwd** [comment]
这个问题解决了，您的这个软件填入slideaddress的那格我填入的是默认的那个地址加上slideaddress的结果，默认的是这个0x0000000100000000，我的slideaddress是0xc0000，结果是0x1000c0000，最后应该填入的地址是0x1000c0000。这样填入，能找到主工程的位置，但是还是找不到framework的位置。

**Comment by fanzwd** [comment]
最后是我的framework没有打开生成dsym的选项导致的，这个问题解决了。不是这个开源软件的问题。
