### ISSUE TITLE
10.12.5

### ISSUE THREAD

**Issue by WangYiOS** [answer-huang/dSYMTools#36]
mac 10.12.5打不开dSYM.app

一打开就闪退

**Comment by WangYiOS** [comment]
已给星星

**Comment by answer-huang** [comment]
麻烦贴下错误日志，谢谢。

**Comment by WangYiOS** [comment]
没想到回复的这么快，惭愧惭愧。。。我以后每天看下您的这个GitHub,顺便问下。。。怎么看 错误日志。。。。

**Comment by answer-huang** [comment]
看下 Console 里面的日志，还有是用的最新的原生写的 dSYM APP 么？可以自己用源码跑起来调试下。

**Comment by WangYiOS** [comment]
不好意思，是我使用的姿势不对，现在可以正常使用了。关闭这个问题吧。。。
