### ISSUE TITLE
大神，请看向这里，问个问题。

### ISSUE THREAD

**Issue by WangYiOS** [answer-huang/dSYMTools#37]
大神，问几个问题哈，您有空了，帮忙解答下，不急。。。

> 第一个问题：

使用咱们的dysm工具时候，我需要粘贴crash的内存地址.
如：zzss   0x00000001003b26fc 0x1000f8000 + 2860796
我需要粘贴zzss对应的 0x00000001003b26fc ，还是 0x1000f8000。

> 第二个问题：

我使用dysm工具时，粘贴了
Thread 0 name:
Thread 0 Crashed:
下的zzss对应内存地址。那么下面的Thread 1 name，Thread 2 name，Thread 3 name等等，它们里面的zzss内存地址是有效的吗？是崩溃的bug吗?我需要去解析吗？

> 下面我贴了一个crash日志。里面有Thread 0 name 到 Thread 4 name的内容，方便您理解我表达的意思。原谅我憋脚的中文。。。

Incident Identifier: E9106930-A281-4B8B-A5DB-D63D15BD7571
CrashReporter Key:   42b849bf0a306e635712f2281a01e579e1759286
Hardware Model:      iPhone8,1
Process:             zzss [2556]
Path:                /private/var/containers/Bundle/Application/EA8C2236-F5A6-4727-8678-574F2255AB72/zzss.app/zzss
Identifier:          com.suteng.zzss
Version:             160 (9.3.1)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2017-07-29 16:19:22.22 +0800
Launch Time:         2017-07-29 16:17:16.16 +0800
OS Version:          iOS 9.3.4 (13G35)
Report Version:      105

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x000000000000003c
Triggered by Thread:  0

Global Trace Buffer (reverse chronological seconds):
0.644542     CFNetwork                 	0x0000000182461480 TCP Conn 0x12d248de0 started
0.777152     CFNetwork                 	0x00000001823bd8e0 TCP Conn 0x12d11db50 SSL Handshake DONE
0.937783     CFNetwork                 	0x00000001823bd7f0 TCP Conn 0x12d11db50 starting SSL negotiation
0.938313     CFNetwork                 	0x000000018245fe7c TCP Conn 0x12d11db50 complete. fd: 18, err: 0
0.939821     CFNetwork                 	0x00000001824613a8 TCP Conn 0x12d11db50 event 1. err: 0
1.020186     CFNetwork                 	0x0000000182461480 TCP Conn 0x12d11db50 started
2.359983     CFNetwork                 	0x00000001823bd8e0 TCP Conn 0x12d0fb270 SSL Handshake DONE
2.377196     CFNetwork                 	0x00000001823bd8e0 TCP Conn 0x2d02d9a0 SSL Handshake DONE
2.383269     CFNetwork                 	0x00000001823bd8e0 TCP Conn 0x12d07b0a0 SSL Handshake DONE
2.517513     CFNetwork                 	0x00000001823bd7f0 TCP Conn 0x12d0fb270 starting SSL negotiation
2.518346     CFNetwork                 	0x000000018245fe7c TCP Conn 0x12d0fb270 complete. fd: 13, err: 0
2.519983     CFNetwork                 	0x00000001824613a8 TCP Conn 0x12d0fb270 event 1. err: 0
2.535649     CFNetwork                 	0x00000001823bd7f0 TCP Conn 0x12d02d9a0 starting SSL negotiation

Thread 0 name:
Thread 0 Crashed:
0   libAVFAudio.dylib             	0x000000018842fddc -[AVAudioSession privateMarkKVOPropertiesDirty:] + 48 (AVAudioSession.mm:1701)
1   libAVFAudio.dylib             	0x000000018842fdd4 -[AVAudioSession privateMarkKVOPropertiesDirty:] + 40 (AVAudioSession.mm:1699)
2   libAVFAudio.dylib             	0x000000018842d998 -[AVAudioSession setCategory:error:] + 168 (AVAudioSession.mm:616)
3   zzss                          	0x00000001003b26fc 0x1000f8000 + 2860796
4   zzss                          	0x00000001003b2618 0x1000f8000 + 2860568
5   libdispatch.dylib             	0x000000018182547c _dispatch_client_callout + 16 (object.m:506)
6   libdispatch.dylib             	0x00000001818262c0 dispatch_once_f + 80 (once.c:60)
7   zzss                          	0x00000001003b25f0 0x1000f8000 + 2860528
8   zzss                          	0x00000001006914f8 0x1000f8000 + 5870840
9   UIKit                         	0x0000000186f51374 -[UIViewController _setViewAppearState:isAnimating:] + 628 (UIViewController.m:3796)
10  UIKit                         	0x0000000186f510e8 -[UIViewController __viewWillAppear:] + 156 (UIViewController.m:3900)
11  UIKit                         	0x00000001870ebe5c -[UINavigationController _startCustomTransition:] + 1052 (UINavigationController.m:1558)
12  UIKit                         	0x0000000186ff7e40 -[UINavigationController _startDeferredTransitionIfNeeded:] + 688 (UINavigationController.m:4698)
13  UIKit                         	0x0000000186ff7b1c -[UINavigationController __viewWillLayoutSubviews] + 60 (UINavigationController.m:4931)
14  UIKit                         	0x0000000186ff7a84 -[UILayoutContainerView layoutSubviews] + 208 (UILayoutContainerView.m:86)
15  UIKit                         	0x0000000186f341e4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 656 (UIView.m:11881)
16  QuartzCore                    	0x00000001848c698c -[CALayer layoutSublayers] + 148 (CALayer.mm:8899)
17  QuartzCore                    	0x00000001848c15c8 CA::Layer::layout_if_needed(CA::Transaction*) + 292 (CALayer.mm:8779)
18  QuartzCore                    	0x00000001848c1488 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32 (CALayer.mm:2524)
19  QuartzCore                    	0x00000001848c0ab8 CA::Context::commit_transaction(CA::Transaction*) + 252 (CAContextInternal.mm:1627)
20  QuartzCore                    	0x00000001848c0818 CA::Transaction::commit() + 500 (CATransactionInternal.mm:416)
21  QuartzCore                    	0x00000001848b9ddc CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80 (CATransactionInternal.mm:769)
22  CoreFoundation                	0x0000000181d90728 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32 (CFRunLoop.c:1620)
23  CoreFoundation                	0x0000000181d8e4cc __CFRunLoopDoObservers + 372 (CFRunLoop.c:1716)
24  CoreFoundation                	0x0000000181d8e8fc __CFRunLoopRun + 928 (CFRunLoop.c:2558)
25  CoreFoundation                	0x0000000181cb8c50 CFRunLoopRunSpecific + 384 (CFRunLoop.c:2814)
26  GraphicsServices              	0x00000001835a0088 GSEventRunModal + 180 (GSEvent.c:2245)
27  UIKit                         	0x0000000186fa2088 UIApplicationMain + 204 (UIApplication.m:3772)
28  zzss                          	0x00000001004e7b84 0x1000f8000 + 4127620
29  libdyld.dylib                 	0x00000001818568b8 start + 4 (start_glue.s:78)

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001819754d8 kevent_qos + 8
1   libdispatch.dylib             	0x00000001818387d8 _dispatch_mgr_invoke + 232 (source.c:2542)
2   libdispatch.dylib             	0x0000000181827648 _dispatch_mgr_thread + 52 (source.c:2573)

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x0000000181973f24 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x0000000181a3ece8 _pthread_cond_wait + 648 (pthread_cond.c:536)
2   Foundation                    	0x000000018271a35c -[NSCondition wait] + 240 (NSLock.m:175)
3   zzss                          	0x0000000101582eac 0x1000f8000 + 21540524
4   zzss                          	0x0000000101583cd4 0x1000f8000 + 21544148
5   libdispatch.dylib             	0x00000001818254bc _dispatch_call_block_and_release + 24 (init.c:760)
6   libdispatch.dylib             	0x000000018182547c _dispatch_client_callout + 16 (object.m:506)
7   libdispatch.dylib             	0x0000000181833914 _dispatch_root_queue_drain + 2140 (inline_internal.h:1063)
8   libdispatch.dylib             	0x00000001818330b0 _dispatch_worker_thread3 + 112 (queue.c:4249)
9   libsystem_pthread.dylib       	0x0000000181a3d470 _pthread_wqthread + 1092 (pthread.c:1990)
10  libsystem_pthread.dylib       	0x0000000181a3d020 start_wqthread + 4 (pthread_asm.s:190)

Thread 3 name:
Thread 3:
0   CFNetwork                     	0x000000018238feb0 0x18238c000 + 16048 (CFObject.cpp:816)
1   CFNetwork                     	0x00000001823c8df4 -[__NSURLSessionLocal _createXCookieStorage] + 116 (LocalSession.mm:980)
2   CFNetwork                     	0x00000001823c9138 -[__NSURLSessionLocal _getCookieHeadersForTask:completionHandler:] + 136 (LocalSession.mm:1061)
3   CFNetwork                     	0x000000018247afb8 HTTPProtocol::asynchronouslyAddCookiesAndContinue(__CFHTTPMessage*) + 344 (Session.h:921)
4   CFNetwork                     	0x00000001824786f0 HTTPProtocol::asynchronouslyCreateAndOpenStream(_CFCachedURLResponse const*) + 280 (HTTPProtocol.cpp:2260)
5   CFNetwork                     	0x00000001824b96a8 ___ZN19URLConnectionLoader27_private_ScheduleOriginLoadEPK12NSURLRequestPK20_CFCachedURLResponse_block_invoke_2 + 72 (URLConnectionLoader.cpp:1782)
6   CFNetwork                     	0x00000001823a7af0 ___ZNK19URLConnectionLoader25withExistingProtocolAsyncEU13block_pointerFvP11URLProtocolE_block_invoke + 32 (URLConnectionLoader.cpp:1118)
7   libdispatch.dylib             	0x000000018182547c _dispatch_client_callout + 16 (object.m:506)
8   libdispatch.dylib             	0x000000018182e7b8 _dispatch_block_invoke + 540 (queue.c:2171)
9   CFNetwork                     	0x00000001823a7ac0 RunloopBlockContext::_invoke_block(void const*, void*) + 36 (CoreSchedulingSet.mm:363)
10  CoreFoundation                	0x0000000181cb867c CFArrayApplyFunction + 68 (CFArray.c:707)
11  CFNetwork                     	0x00000001823a79a4 RunloopBlockContext::perform() + 136 (CoreSchedulingSet.mm:317)
12  CFNetwork                     	0x00000001823a7864 MultiplexerSource::perform() + 312 (CFNRunLoopMultiplexer.c:282)
13  CFNetwork                     	0x00000001823a7690 MultiplexerSource::_perform(void*) + 68 (CFNRunLoopMultiplexer.c:47)
14  CoreFoundation                	0x0000000181d9109c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24 (CFRunLoop.c:1761)
15  CoreFoundation                	0x0000000181d90b30 __CFRunLoopDoSources0 + 540 (CFRunLoop.c:1807)
16  CoreFoundation                	0x0000000181d8e830 __CFRunLoopRun + 724 (CFRunLoop.c:2536)
17  CoreFoundation                	0x0000000181cb8c50 CFRunLoopRunSpecific + 384 (CFRunLoop.c:2814)
18  CFNetwork                     	0x0000000182439bcc +[NSURLConnection(Loader) _resourceLoadLoop:] + 412 (NSURLConnection.mm:325)
19  Foundation                    	0x00000001827afe4c __NSThread__start__ + 1000 (NSThread.m:1134)
20  libsystem_pthread.dylib       	0x0000000181a3fb28 _pthread_body + 156 (pthread.c:656)
21  libsystem_pthread.dylib       	0x0000000181a3fa8c _pthread_start + 156 (pthread.c:692)
22  libsystem_pthread.dylib       	0x0000000181a3d028 thread_start + 4 (pthread_asm.s:197)

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x0000000181973f24 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x0000000181a3ece8 _pthread_cond_wait + 648 (pthread_cond.c:536)
2   zzss                          	0x00000001014a4c1c 0x1000f8000 + 20630556
3   zzss                          	0x000000010148e33c 0x1000f8000 + 20538172
4   zzss                          	0x00000001014a1800 0x1000f8000 + 20617216
5   zzss                          	0x00000001014a5330 0x1000f8000 + 20632368
6   libsystem_pthread.dylib       	0x0000000181a3fb28 _pthread_body + 156 (pthread.c:656)
7   libsystem_pthread.dylib       	0x0000000181a3fa8c _pthread_start + 156 (pthread.c:692)
8   libsystem_pthread.dylib       	0x0000000181a3d028 thread_start + 4 (pthread_asm.s:197)

**Comment by answer-huang** [comment]
http://blog.csdn.net/xiaofei125145/article/details/50408051
看下这篇文章吧，作者写的比较清晰。
