### ISSUE TITLE
拖入.DSYM文件后，右侧请选择CPU类型无显示

### ISSUE THREAD

**Issue by Jakiro-Fan** [answer-huang/dSYMTools#39]
将打包生成的.DSYM文件拖入后，点击该文件，右侧“请选择cpu类型”无任何显示，请指教？

**Comment by answer-huang** [comment]
有选中左侧的 dsym 么。

**Comment by Jakiro-Fan** [comment]
选中了，还是无任何显示。

**Comment by answer-huang** [comment]
能把文件发我调试下么。 aihoo91@gmail.com

**Comment by Jakiro-Fan** [comment]
已通过邮件发送到您邮箱了。

**Comment by answer-huang** [comment]
@Jakiro-Fan  你是不是用的 wxPython 这个目录下的 app，不要用这个，自己用源码编译以下，wxPython 是最初的老版本。

**Comment by Jakiro-Fan** [comment]
项目中没有用到Python语音，打包的时候就是用xcode直接archive的。

**Comment by answer-huang** [comment]
我这边试了下是可以的，看下会不会是路径里面包含什么特殊的字符之类的。

**Comment by Jakiro-Fan** [comment]
在桌面重新建了个全英文文件存储.xcarchive文件，并在该文件拖拽到分析工具中，再点击该文件，右侧“请选择cpu类型“仍无显示，通过邮件又给您发了过程中的图片。

**Comment by Jakiro-Fan** [comment]
另外，是通过运行xcode启动的分析工具

**Comment by answer-huang** [comment]
有输出什么错误么，我这儿调试都是正常的。

**Comment by xeroxmx** [comment]
10.12.6 右边无法显示cpu类型

**Comment by Jakiro-Fan** [comment]
问题已解决，原因：装的xcode好多个版本，但是没有一个以“Xcode”进行命名。该分析工具，需要这个路径/Applications/Xcode.app/Contents/Developer
