### ISSUE TITLE
10.10 拖文件进去就崩溃啊, GUI 部分不开源吗

### ISSUE THREAD

**Issue by GreatFireWall** [answer-huang/dSYMTools#4]

**Comment by answer-huang** [comment]
你好，能提供一下机型，以及崩溃时的截图吗？
代码是开源的啊，GUI 实现是用的 wxPython，环境配好了就可以运行起来了。

**Comment by GreatFireWall** [comment]
mac os x 10.10. 有无办法拿到崩溃信息?

**Comment by Hanmis** [comment]
mac os x 10.9.2 无法分析错误信息
xcode Version 6.1.1 打包的 archive 提取里面的dSYM

**Comment by answer-huang** [comment]
@Hanmis  你好，是不是 arm64 下的错误，这个问题已经修复，我会重新发一个包出来。

**Comment by answer-huang** [comment]
@GreatFireWall  你好，如果软件能正常打开的话，麻烦查一下路径中是否存在空格，如果路径中有空格，是会导致应用崩溃的，这一块一直还没处理。

**Comment by GreatFireWall** [comment]
是的, 是空格问题, 可以让程序处理空格吗, 我的系统是中文版生成的 archive 默认就是中文带空格的名字.

**Comment by answer-huang** [comment]
@Hanmis  软件已经更新，麻烦下载 1.0.2 版本。http://pan.baidu.com/s/1o65gV4Q

**Comment by GreatFireWall** [comment]
好的, 谢谢.

**Comment by answer-huang** [comment]
@GreatFireWall  1.0.3 已经处理了路径中包含空格的问题了。

**Comment by GreatFireWall** [comment]
1.0.2 试过已经解决空格问题,  1.0.3 有链接发一下吗, 谢谢

**Comment by answer-huang** [comment]
@GreatFireWall  http://pan.baidu.com/s/1mg01Qha
