### ISSUE TITLE
一个项目打包的DSYM文件解析出的UUID 都一样? 

### ISSUE THREAD

**Issue by Marcusias** [answer-huang/dSYMTools#40]
![61503026081_ pic](https://user-images.githubusercontent.com/13980779/30414144-b62c5ff0-9954-11e7-817e-6720bb243b07.jpg)
RT,xcode卸载了几次都是这样....

**Comment by Marcusias** [comment]
打包一次之后解析得到的UUID都不变了....

**Comment by answer-huang** [comment]
应该不一样的。

**Comment by answer-huang** [comment]
路径里面空格去掉试试，可能路径解析有问题，所以一直保留的之前的结果。

**Comment by Marcusias** [comment]
使用源码发现打印这个错误:
"error: unable to open '(null)': No such file or directory"
怎么解决?

**Comment by answer-huang** [comment]
输出下路径，应该是路径包含特殊字符了，但是这块应该处理过了。

**Comment by Marcusias** [comment]
打印后发现,解析不是对应应用的XXX.app.dSYM 文件,而是我使用的第三方的 ZXingObjC.framework.dSYM 文件,应该是是忽略了dSYMs 下会有多个dSYM文件的情况~~

**Comment by Marcusias** [comment]
修改 [[fileURLs.relativePath lastPathComponent] hasSuffix:@"dSYM"]   为
        [[fileURLs.relativePath lastPathComponent] hasSuffix:@"app.dSYM"]  解决~~~~

**Comment by answer-huang** [comment]
我修复下。
