### ISSUE TITLE
作者您好, bugly收集的错误地址, 要如何解析?

### ISSUE THREAD

**Issue by pt4lwj** [answer-huang/dSYMTools#41]
我们公司的APP, 使用了2套bug收集系统: 友盟 和 bugly.

例如有一个崩溃, 两个平台同时接收到报错信息.
这是友盟的堆栈信息:
![image](https://user-images.githubusercontent.com/10663197/30424335-35a01fa6-9978-11e7-87b8-297b62344e37.png)

工具可以正确识别友盟的堆栈信息.
![image](https://user-images.githubusercontent.com/10663197/30425077-8e93eb54-997a-11e7-999b-0277d725bc38.png)

这是bugly经过自动还原的堆栈信息:
![image](https://user-images.githubusercontent.com/10663197/30424425-8a8891e2-9978-11e7-9a12-428846f90a88.png)

这是bugly为还原的原始堆栈信息:
![image](https://user-images.githubusercontent.com/10663197/30424488-b3b328e8-9978-11e7-8ca7-442163b70869.png)

这里可见, 第一张图和第四张图所对应的是同一个错误. 我要如何使用这个工具找到bugly平台的错误堆栈呢?

**Comment by answer-huang** [comment]
能提供下 bugly 里面有没有类似 slide address 之类的地址么，我没用过 bugly。

**Comment by pt4lwj** [comment]
您好, 我回去看了一下, bugly并没有提供slide address. 
但是我觉得他们这两个平台给出的报错地址, 是有一定联系的.

**Comment by answer-huang** [comment]
这个应该是友盟做了地址转换，因为没有 ASLR 时 ARM64 架构的加载地址是从 0x0000000100000000 开始的，有了 ASLR 机制后，每次都会随机加上一个偏移量，友盟估计为了方便对slice address 做了转换，所以在 arm64 架构的手机上，友盟收集到的 slide address 全是 0x0000000100000000,armv7 上全是 0x00004000。

**Comment by pt4lwj** [comment]
看样子, 想要定位到bugly产生的错误. 不太容易, 这对于开发者来说, 是一件比较难受的事情.
单纯从友盟和bugly捕获到的同一个错误地址分析他们之间存在的联系, 似乎是一件很难的事.

**Comment by answer-huang** [comment]
http://blog.csdn.net/xiaofei125145/article/details/50408051
看下这篇文章吧，是可以自己算出来的，bugly 给出来的应该就是原始的内存地址，而友盟只是做了下转换。
