### ISSUE TITLE
xcode9打包出来的xcarchive不能分析

### ISSUE THREAD

**Issue by shaveKevin** [answer-huang/dSYMTools#45]
使用xcode 9 archive出来的xcarchive 不能进行分析

**Comment by shaveKevin** [comment]
![2017-11-15 08 48 55](https://user-images.githubusercontent.com/9313522/32813060-dfd689ae-c96d-11e7-98d9-50e1b6e86f6e.jpg)

**Comment by answer-huang** [comment]
能否提供个 archive 文件看下，或者也可以自己用源码调试下。

**Comment by shaveKevin** [comment]
问题已经解决 是我xcode 9 设置的问题。xcode 9 archieve 出来的xcarchive dsyms 里面为空，导致不能分析。解决方案：
