### ISSUE TITLE
体验优化

### ISSUE THREAD

**Issue by Beyond-Chao** [answer-huang/dSYMTools#46]
1. 一次只能解析一个错误内存地址，希望支持同时解析多个

2. 能拿到做好的崩溃原因嘛？比如-[__NSArrayM insertObject:atIndex:]: object cannot be nil，或者Unrecognized Selector Crash, 就更好了，需要提供完整的.crash文件吗？如果这样的话

**Comment by answer-huang** [comment]
1. 一次解析多个的话不太友好，因为一般错误堆栈信息并不是一次性就能定位到错误的，所以需要尝试根据多个错误地址寻找最终导致错误的行数。
2. 只要能提供错误地址和 archive 文件就能找到，有了 crash 文件需要自己计算 slide address，具体怎么计算可以百度下
