### ISSUE TITLE
从手机导出的crash日志,怎么获得slide address

### ISSUE THREAD

**Issue by huapeng222** [answer-huang/dSYMTools#5]
找了半天没有找到,只有友盟的记录中能看到这个东西

**Comment by answer-huang** [comment]
slide address就是应用加载的起始地址，crash 日志里面错误堆栈信息里面每行应该有三个地址，中间那个就是了：370 appName   0x000000010067ec5c 0x1000c8000 + 5991516。这行错误日志里面，0x1000c8000 就是要的 slide address了(即假设的应用加载起始地址)，然后偏移了 5991516之后，调用了应用里面另一个方法，这个方法对应的地址是：0x000000010067ec5c，所以如果转换成10进制的话，0x000000010067ec5c = 0x1000c8000 + 5991516。

**Comment by huapeng222** [comment]
谢谢
