### ISSUE TITLE
希望可以直接符号化整个crash文件，一行一行的复制粘贴调试比较慢，如果可以整个文件输出看起来就更方便了。

### ISSUE THREAD

**Issue by yumengqing** [answer-huang/dSYMTools#51]
希望可以直接符号化整个crash文件，一行一行的复制粘贴调试比较慢，如果可以整个文件输出看起来就更方便了。

**Comment by Mamong** [comment]
如果是crash文件符号化，你应该使用symbolicatecrash。
dSYMTools只是查看某个地址对应的符号，用途不同。otos也是这个道理。

**Comment by answer-huang** [comment]
如果是 crash 文件, Xcode 默认就有这个功能了哟, 这个项目是为了方便处理各种错误平台收集过来的 bug 日志.
