### ISSUE TITLE
无法选择CPU类型

### ISSUE THREAD

**Issue by epldlnwynn** [answer-huang/dSYMTools#52]
左则已选，右则没有显示CPU类型，请问题是什么问题

系统版本：macOS Mojave 版本：10.14.6
Xcode版本：10.3

**Comment by answer-huang** [comment]
对不起, 这个项目已经很久不维护了, 你这个问题应该是路径包含中文或者空格导致文件解析失败了, 之前处理过类似的问题,  如果你是做 iOS 开发, 建议源代码调试下.
