### ISSUE TITLE
默认Slide Address从哪儿来的呢？

### ISSUE THREAD

**Issue by AppLog** [answer-huang/dSYMTools#53]

**Comment by Mamong** [comment]
它这个其实是模块加载后的虚拟内存起始地址，主模块是0x0000000100000000。其他模块就不是这个值了。

**Comment by answer-huang** [comment]
![image](https://user-images.githubusercontent.com/1219398/75786514-65113b00-5da0-11ea-9285-8479768c0c48.png)
