### ISSUE TITLE
新版友盟报错的信息怎么定位代码，求指教

### ISSUE THREAD

**Issue by xuchunyu-caibaoshuo** [answer-huang/dSYMTools#55]

**Comment by liunianhuaguoyanxi** [comment]
Fork后优化了定位流程： https://github.com/liunianhuaguoyanxi/dSYMTools

**Comment by answer-huang** [comment]
@liunianhuaguoyanxi  这个项目已经很久不维护了, 而且新版的友盟也没用过,  可以发个 PR 我合并到仓库里, 谢谢.
