### ISSUE TITLE
分析出来的地址和目标地址不一样

### ISSUE THREAD

**Issue by LuckyChen99** [answer-huang/dSYMTools#57]
我特意在一个类中写了错误代码, 上传appStore, 测试上传数据后, 在bugly中对应将地址拷贝到工具中分析, 分析出来的地址跟崩溃的类不一样, 请问这个该怎么解决

**Comment by answer-huang** [comment]
bugly 里面有对基地址进行处理吗. 应该是基地址没对应上.

**Comment by LuckyChen99** [comment]
这个我没仔细看过，得再分析一下了




| |
cw1016728730
|
|
邮箱：cw1016728730@163.com
|

Signature is customized by Netease Mail Master

在2020年03月03日 19:04，answer-huang 写道：

bugly 里面有对基地址进行处理吗. 应该是基地址没对应上.

**Comment by answer-huang** [comment]
![image](https://user-images.githubusercontent.com/1219398/75785748-2f1f8700-5d9f-11ea-8124-c7f73dfad7aa.png)

用 bugly 试了下, 注意两个点:
1. bugly 后台貌似没有显示出来 dsym 的 UUID, 这个你自己本地找文件的时候, 一定要找到对应的上的.
2. Slide Address 是红色箭头那个.
3. 错误的内存地址是 Slide Address + 数据. (这个地方结果要自己换算成 十六进制, 当时这个地方没有做处理是为了兼容更多的错误收集平台, 有的平台是默认给出计算之后的地址)
