### ISSUE TITLE
友盟crash报告里Slide Address为null怎么破？

### ISSUE THREAD

**Issue by wonderffee** [answer-huang/dSYMTools#6]
看地址是64位地址，但报告下方显示的是Slide Address: (null)，不输Slide Address点分析没有反应
觉得友盟的crash报告真是个废物。。。

**Comment by answer-huang** [comment]
或者你从类似的日志里面看一下有没有 Slide Address，同一个版本对应的日志，Slide Address 应该是一样的。普遍情况下 armv7 下的 Slide Address 应该是 0x00004000，arm64 下的 Slide Address 应该是 0x0000000100000000 。
