### ISSUE TITLE
为什么不能输入偏移地址？

### ISSUE THREAD

**Issue by LiweiDong** [answer-huang/dSYMTools#64]
<img width="518" alt="1212" src="https://user-images.githubusercontent.com/1669848/158339994-0b0dbdb1-9078-492b-b81b-a47b5f1a5525.png">

**Comment by answer-huang** [comment]
之前做这个的时候记得 arm64 的错误日志好像都是处理成一样的偏移地址了, 所以做了默认处理, 如果有问题可以下载源码到本地运行, 修改下偏移地址.
