### ISSUE TITLE
点击分析没有反应

### ISSUE THREAD

**Issue by liudehuaGithub** [answer-huang/dSYMTools#65]
我导入.dsYM文件 点击分析没有反应，控制台也没有打印任何信息

可执行文件的UUID是对的

**Comment by answer-huang** [comment]
方便提供下 dsym 文件和错误地址到 aihoo91@gmail.com 吗？

**Comment by liudehuaGithub** [comment]
已发送！谢谢

**Comment by liudehuaGithub** [comment]
你好！你这个邮箱我发不出去，发了2次都被退回来了，说我发的垃圾邮件
