### ISSUE TITLE
分析结果还是没对应代码啊

### ISSUE THREAD

**Issue by gaojiewan** [answer-huang/dSYMTools#66]
我这边输入友盟上的内存地址和偏移量之后分析出来的还是友盟上的东西：0x00000001044aa13c，并没有对应代码是咋回事啊？

**Comment by answer-huang** [comment]
> 我这边输入友盟上的内存地址和偏移量之后分析出来的还是友盟上的东西：0x00000001044aa13c，并没有对应代码是咋回事啊？

麻烦贴个截图看下.

**Comment by gaojiewan** [comment]
<img width="516" alt="12" src="https://user-images.githubusercontent.com/25924757/203190672-d1fa8639-4dfb-48f8-b787-801b6c27fed6.png">
<img width="512" alt="11" src="https://user-images.githubusercontent.com/25924757/203190678-bdac489a-a9f1-4bf0-b771-77c12efe82d9.png">
感谢回复，我这又找了两个，确实定位到了代码，但是搜了一下项目没这两个方法，这种是第三方SDK的吗，那怎么定位到调用的地方呢？

**Comment by answer-huang** [comment]
> <img alt="12" width="516" src="https://user-images.githubusercontent.com/25924757/203190672-d1fa8639-4dfb-48f8-b787-801b6c27fed6.png">
> 
> <img alt="11" width="512" src="https://user-images.githubusercontent.com/25924757/203190678-bdac489a-a9f1-4bf0-b771-77c12efe82d9.png">
> 
> 感谢回复，我这又找了两个，确实定位到了代码，但是搜了一下项目没这两个方法，这种是第三方SDK的吗，那怎么定位到调用的地方呢？

你在友盟上复制的错误内存地址前面对应的可执行文件显示的是你们自己的应用吗 ？

如果是你们自己应用，那还有可能是定位错误了，你要看下友盟错误里面的 slide address 是不是显示的  0x0000000100000000

**Comment by gaojiewan** [comment]
<img width="281" alt="1" src="https://user-images.githubusercontent.com/25924757/203462753-21ce6800-2881-45aa-9945-593974cc5d25.png">
<img width="275" alt="2" src="https://user-images.githubusercontent.com/25924757/203462759-8eba2192-d7f9-4669-8699-e0e440560ee6.png">
可执行文件应该是我们应用的，我们是集成了腾讯的sdk的，但是看不到他们源码，这个定位出来的方法也搜不到，所以还是没办法排查bug；
然后这个0x00000001d8e85948我换成友盟上的分析出来的就不行了，还是用的默认的。

**Comment by answer-huang** [comment]
> <img alt="1" width="281" src="https://user-images.githubusercontent.com/25924757/203462753-21ce6800-2881-45aa-9945-593974cc5d25.png">
> 
> <img alt="2" width="275" src="https://user-images.githubusercontent.com/25924757/203462759-8eba2192-d7f9-4669-8699-e0e440560ee6.png">
> 
> 可执行文件应该是我们应用的，我们是集成了腾讯的sdk的，但是看不到他们源码，这个定位出来的方法也搜不到，所以还是没办法排查bug； 然后这个0x00000001d8e85948我换成友盟上的分析出来的就不行了，还是用的默认的。

如果方便的话，可以把 dsym 文件 和 友盟 的日志发一份到我的邮箱（aihoo91@gmail.com），我来看下。
