### ISSUE TITLE
友盟的崩溃分析不出错误代码，直接返回一个数字

### ISSUE THREAD

**Issue by smile678** [answer-huang/dSYMTools#67]
![ym1683527980899](https://user-images.githubusercontent.com/43466858/236752542-f6efc25f-1133-497a-b3d9-e2f90aac7a20.jpg)
![ym1683527965788](https://user-images.githubusercontent.com/43466858/236752579-d90455dd-6e67-4603-bc75-af8090037eee.jpg)
如图，分析不出错误代码，尝试了0x00000001049f2278和520844、0x000000010494ea34和2468404、0x000000010494e5cc和2467276都不行，UUID和Slide Address是根据文件自动生成的，且都和友盟里面一致

**Comment by answer-huang** [comment]
`默认 Slide Address` 改成和 `错误信息内存地址` 一样即可.
