### ISSUE TITLE
填偏移量的意义是什么呢

### ISSUE THREAD

**Issue by Ox8BADFOOD** [answer-huang/dSYMTools#68]
两种填写方法
第一种方法：填偏移量
![image](https://github.com/answer-huang/dSYMTools/assets/20883315/16661b39-992b-4f35-8fd3-f76f9d9a7171)

第二种方法：不填填偏移量，直接填上偏移量与错误信息内存地址的和，如下图：
![image](https://github.com/answer-huang/dSYMTools/assets/20883315/182a3aa1-077b-4317-8e79-bf5e730d2fa3)
![image](https://github.com/answer-huang/dSYMTools/assets/20883315/cb304c78-70d9-4925-8f7d-d8c98c7a09b7)

方法一和方法二算出来的都是对的。方法二中的错误地址  =  方法一中的错误信息内存地址 + 偏移量。

问题一：方法一和方法二两种用法是不是都正确？

问题一：在方法一中，我发现  默认 Slide Address  和  错误信息内存地址  填的是一样的。并且log中别的位置的  错误信息内存地址  和  默认 Slide Address  也是一样的，不会变。在方法一中那我是不是可以认为两者等同？真实的错误地址是的错误信息地址加偏移量量？对比方法二，方法一这样拆开填写有什么意义？

这是闪退的堆栈
![image](https://github.com/answer-huang/dSYMTools/assets/20883315/bd47c321-dbea-49d8-b129-a1237f684ec8)
这是起始地址
![image](https://github.com/answer-huang/dSYMTools/assets/20883315/6782be13-7d0c-49ae-9236-d4d3320a2b70)

**Comment by answer-huang** [comment]
需要填偏移量主要是为了适配之前 umeng 上收集到的错误信息, 你这个错误应该是系统收集过来的吧 ?  我记得友盟上的数据没这么全.
方法一 和 方法二 都是可以的.
