### ISSUE TITLE
app/dSYM 运行不了

### ISSUE THREAD

**Issue by jiazufei** [answer-huang/dSYMTools#8]
我试着控制台运行 python setup.py py2app
生成 的dist下面有个文件夹，里边有个dSYM，双击运行提示dSYM Error 
诊断信息是这样的
15/8/7 上午9:22:29.587 com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
15/8/7 上午9:22:30.112 dSYM[745]: GetDYLDEntryPointWithImage(/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit,_NSCreateAppKitServicesMenu) failed.
15/8/7 上午9:22:32.277 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:32.277 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:32.278 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:32.278 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:32.932 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:32.932 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:32.932 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:32.932 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:39.491 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:39.491 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:39.491 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:39.492 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:41.115 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:41.115 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:41.115 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:41.116 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:41.908 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:41.908 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:41.908 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:41.908 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:42.803 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:42.803 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:42.804 Dock[201]: CGSConnectionByID: 0 is not a valid connection ID.
15/8/7 上午9:22:42.804 Dock[201]: Invalid Connection ID 0
15/8/7 上午9:22:46.649 WindowServer[134]: CGXGetConnectionProperty: Invalid connection 118719
15/8/7 上午9:22:46.649 WindowServer[134]: CGXGetConnectionProperty: Invalid connection 118719
15/8/7 上午9:22:58.673 dSYM[752]: dSYM Error

**Comment by jiazufei** [comment]
系统版本是10.10.3

**Comment by answer-huang** [comment]
我根据日志查了一下，应该是系统的问题。你可以通过关键词 Yosemite GetDYLDEntryPointWithImage 去 Google 一下。
